[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
cargo-dist-version = "0.31.0"
ci = "github"
installers = ["shell", "powershell", "homebrew"]
targets = ["aarch64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
install-path = "CARGO_HOME"
hosting = "github"
install-updater = false
pr-run-mode = "skip"
allow-dirty = []
